project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R"
  page-navigation: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics in R"
        contents:
          - href: syntax.qmd
          - href: gettinghelp.qmd
          - href: Rascalculator.qmd
          - href: objects.qmd
          - href: functions.qmd
          - href: yourfunction.qmd
          - href: subsetting.qmd
          - href: quarto.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

